
[[Part1]]
= Test Part 1

== Test Chapter

This is a test paragraph in a chapter

=== Test Section 1

This is a test paragraph in a section

.Callout Testing Example
======================================================================
----------------------------------------------------------------------
First item <1>
Second item <2>
Third item <3>
----------------------------------------------------------------------
<1> First item
<2> Second item
<3> Third item
======================================================================

[[Test_Section_2]]
=== Test Section 2

indexterm:[Big Cats, Tiger]

This is a test paragraph in a section 2

. listitem text

[NOTE]
======================================================================
Notes are tips, shortcuts or alternative approaches to the task at
hand. Ignoring a note should have no negative consequences, but you
might miss out on a trick that makes your life easier.
======================================================================

[IMPORTANT]
======================================================================
Important boxes detail things that are easily missed: configuration
changes that only apply to the current session, or services that need
restarting before an update will apply.  Ignoring a box labeled
'Important' won't cause data loss but may cause irritation and
frustration.
======================================================================

[WARNING]
======================================================================
Warnings should not be ignored. Ignoring warnings will most likely
cause data loss.
======================================================================


[[Part2]]
= Test Part 2

== Test Chapter

This is a test paragraph in a chapter

[[Test_Section_1]]
=== Test Section 1

This is a test paragraph in a section

.Callout Testing Example
======================================================================
----------------------------------------------------------------------
First item <1>
Second item <2>
Third item <3>
----------------------------------------------------------------------
<1> First item
<2> Second item
<3> Third item
======================================================================

=== Test Section 2

indexterm:[Big Cats, Tiger]

This is a test paragraph in a section 2

. listitem text

[NOTE]
======================================================================
Notes are tips, shortcuts or alternative approaches to the task at
hand. Ignoring a note should have no negative consequences, but you
might miss out on a trick that makes your life easier.
======================================================================

[IMPORTANT]
======================================================================
Important boxes detail things that are easily missed: configuration
changes that only apply to the current session, or services that need
restarting before an update will apply.  Ignoring a box labeled
'Important' won't cause data loss but may cause irritation and
frustration.
======================================================================

[WARNING]
======================================================================
Warnings should not be ignored. Ignoring warnings will most likely
cause data loss.
======================================================================

[[Index]]
= Index
