idforge-modules-hello(1)
========================
Alain Reguera Delgado <alain.reguera@gmail.com>

Name
----

idforge-modules-hello - Print a greeting and exit successfully.

Synopsis
--------

idforge hello [ OPTIONS ] [ GREETING ]

Description
-----------

The _idforge hello_ command prints the arguments you provide in the
command-line to the standard output and exits successfully.  It
provides several options to let you control how the output message is
printed to standard output. Each of these options is intentionally
written to illustrate specific ways of using modules inside the
_idforge_ script.  See the <<options>>.

[[options]]
Options
-------

The _idforge hello_ command accepts the following options:

*-h, --help*::
    Shows command's documentation (this page).

*-v, --version*::
    Shows command's version and legal status.

*-s, --description*::
    Shows command's brief description.

*-l, --lower*::
    Shows message in lowercase. The final output is printed out all in
    one line.

*-u, --upper*::
    Shows message in uppercase. The final output is printed out all in
    one line.

*-c, --camel*::
    Shows messages in camel-case (e.g., "HeLlO").  The output is
    printed one character per line to describe how execution of
    sibling modules work inside idFORGE library.  Notice that, when
    the final output is printed, punctuation marks doesn't count for
    formating.

*-r, --random*::
    Shows message in a random order (e.g., "HHHel").  The final output
    is printed one character per line to describe how recursive
    execution of sibling modules work.

The _idforge hello_ command is also affected by options passed to
_idforge_ script. See, _idforge_ script documentation to know what
these options are.

Examples
--------

.Debug execution environment of parent and child modules
----------------------------------------------------------------------
idforge --debug hello --lower Hello
----------------------------------------------------------------------

.Debug execution environment of parent, child and sibling modules
----------------------------------------------------------------------
idforge --debug hello --camel Hello
----------------------------------------------------------------------

Authors
-------

Written by {author} <{email}>

Copyright
---------

Copyright (C) =COPYRIGHT_YEAR_LAST= CentOS Artwork SIG

idforge-modules-hello is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

idforge-modules-hello is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with idforge-modules-hello; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

// vim: set syntax=asciidoc:
