= idforge(1)
Alain Reguera Delgado <alain.reguera@gmail.com>
idFORGE Framework =MANPAGE_VERSION=, =MANPAGE_YEAR=: =MANPAGE_DESCRIPTION=
:man source: idFORGE Framework
:man version: =MANPAGE_VERSION=
:man manual: User Commands

== Name

idforge - =MANPAGE_DESCRIPTION=

== Synopsis

----------------------------------------------------------------------
=MANPAGE_SYNOPSIS=
----------------------------------------------------------------------

== Description

The *{doctitle}* command is written in Bash using a modular design
specially conceived to gear the work of graphic designers, translators
and documentation writers in a way they can collaborate consistently
one another in a decentralized environment ruled by the normative
specifications of a particular community or organization that is very
interested in making its visual identity manual and the files
necessary for its implementation a community effort.

From an organization visual identity manager's point of view, the
idFORGE Framework results useful to:

- Consolidate an effective and efficient community enrolment in the
  process of building the organization's own visual identity and its
  further implementation.

- Consolidate an effective and efficient procedure to propagate new
  visual styles (a.k.a., artistic motifs) to different visual
  manifestations where the organization shows its existence on (e.g.,
  the organization's visual identity manual and the files for
  implementing it in a specific GNU/Linux distribution).  This, grants
  the visual consistency which is necessary to implement a monolithic
  corporate visual identity structure correctly.

From a graphic designer point of view, the idFORGE Framework results
useful to reproduce a particular organization's visual identity manual
and the files necessary for its implementation using arbitrary visual
styles but a consistent visual structure.  To do so, you need to go
through the following steps:

. Create a workplace using the *idforge-prepare(1)* command. This
  replicates the organization's visual identity structure so you can
  customize it. The organization's visual identity structure is
  normally available after installing the organization's identity
  package in the system.

. Design the organization new look using graphic design tools like
  GIMP and Inkscape. This is the images in PNG format that will be
  used as background to reinforce the visual connection between
  different visual manifestations.

. Rebuild the organization's visual identity manual using the
  *idforge-render(1)* command.

== Options

The *{doctitle}* command interprets option arguments based in the
position they are written in the command-line. When the option
argument is written before the command argument, it is interpreted
directly by *{doctitle}* initialization script and it is considered a
common option.  When the option argument is written after the command
argument, it is interpreted by the related command and it is
considered a specific options to that command instead.

Common options affect the entire execution environment of *{doctitle}*
script, while specific options affect only the execution environment
of the command that interprets them. The specific options are
described in the man page of the command they pertain to.

include::Commons/options.inc[]

*-d, --debug*::
    Runs *{doctitle}* in debugging mode. This option is very useful if
    you want to get a closer look to the way *{doctitle}* modules are
    opened and closed at execution time. For more information about
    *{doctitle}* modules, see *idforge-modules(5)* manual.

*-q, --quiet*::
    Runs the script quietly. This option reduces the amount of
    information *{doctitle}* prints on the screen.

*-y, --yes*::
    Runs the script in affirmative mode. This is answering positively
    to all boolean questions. This option is useful when you run the
    *{doctitle}* script with the *--quiet* option.

When no argument is provided to *{doctitle}*, it prints the usage
information including the list of all modules available. This is also
true when the only argument provided to *{doctitle}* is a valid module,
in which case the module's usage information is printed instead.

Exit Status
-----------

The *{doctitle}* command ends its execution with one of the following
exit status:

* 0 -- Exit successfully without errors.
* 1 -- Exit with errors.

include::Commons/environment.inc[]

include::Commons/author.inc[]

include::Commons/bugs.inc[]

include::Commons/copyright.inc[]

include::Commons/also.inc[]

== Reference

The conceptual ideas about corporate identity are taken from:

*Wikipedia*::
    http://en.wikipedia.org/Corporate_identity[Corporate identity] and
    related pages.

*Wally Olins, Corporate Identity*::
    Making business strategy visible through design
    (ISBN 9780875842509)

// vim: set syntax=asciidoc:
