*-h, --help*::
    Prints documentation (this page).

*-v, --version*::
    Prints version and legal status.

*-s, --description*::
    Prints brief description in one line.

[NOTE]
======================================================================
In case no argument is provided after the command, a brief usage
description will be displayed with the command-line structure.
======================================================================
